### ISSUE TITLE
With Chef 11.x, node attributes now have to have a precedence level set

### ISSUE THREAD

**Issue by bknowles** [jonlives/knife-bulkchangeenvironment#1]
Looks like this code hasn't changed in two years, which means that this error message makes perfect sense.  Unfortunately, the knife-flip plugin has a different problem, so I can't use that one either.

Anyway, the specific error message I get is:

```
ERROR: knife encountered an unexpected error
This may be a bug in the 'node bulk change environment' knife command or plugin
Please collect the output of this command with the \`-VV\` option before filing a bug report.
Exception: Chef::Exceptions::ImmutableAttributeModification: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like \`node.default["key"] = "value"'
```

Let me know if you want the -VV output, and if so where I should put it.  Thanks!

**Comment by jonlives** [comment]
Pushed knife-bulkchangeenvironment-0.1.1 to rubygems, with a fix for this issue. Thanks for reporting it!
